# Generated by Django 5.1.1 on 2024-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casserole',
            name='recipe',
        ),
        migrations.AddField(
            model_name='casserole',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='casserole',
            name='instructions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='casserole',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
